### ISSUE TITLE
Upload file failed

### ISSUE THREAD

**Issue by HoxinhLuo** [yuhixyz/Private-Netdisk#1]
![image](https://user-images.githubusercontent.com/23025747/148485320-12465312-17f4-41d7-9ad2-3432b963dc62.png)
文件上传失败，一直都是这样

**Comment by yuhixyz** [comment]
1. settings文件夹下的dev.py中需要配置 COS_SECRET_ID, COS_SECRET_KEY, APPID，需要自行在腾讯云对象存储获得，我写的默认配置是随便打的
<img width="1269" alt="cos2" src="https://user-images.githubusercontent.com/50203860/148491298-f991a76a-9cc8-4c46-a3cf-a4f12c750864.png">

<img width="1270" alt="cos" src="https://user-images.githubusercontent.com/50203860/148491158-4915ea17-df43-4778-8eb3-48cc537cd5ea.png">

2. 看你的截图，你登录的账户疑似是 python manage.py creatersuperuser 创建的管理员账户，你需要到后台增加一个用户，再用该用户登录网站，再测试上传即可。至于管理员账户为什么一开始上传失败，这应该是个bug:(2333，我刚测试的时候也发现了，但是在127.0.0.1/admin后台用户管理处增加用户后，用新用户登录没有出现上传失败的情况。

3. 另外，本项目只是个人练习django的产物，线上部署过一段时间后就转用阿里云盘去了，毕竟功能实在太少了。

**Comment by HoxinhLuo** [comment]
能否改到本地存储，或者添加存储选项

**Comment by yuhixyz** [comment]
no
